name: Build and Publish storybook to GitHub Pages

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches:
      - "main"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
      with:
        path: ./storybook-static
